package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"go-ocs/internal/backend/graphql/model"
)

// ChargingTraceList is the resolver for the chargingTraceList field.
func (r *queryResolver) ChargingTraceList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.ChargingTrace, error) {
	panic(fmt.Errorf("not implemented: ChargingTraceList - chargingTraceList"))
}

// CountChargingTrace is the resolver for the countChargingTrace field.
func (r *queryResolver) CountChargingTrace(ctx context.Context, filter *model.FilterRequest) (int, error) {
	panic(fmt.Errorf("not implemented: CountChargingTrace - countChargingTrace"))
}

// ChargingTraceByID is the resolver for the chargingTraceById field.
func (r *queryResolver) ChargingTraceByID(ctx context.Context, traceID string) (*model.ChargingTrace, error) {
	panic(fmt.Errorf("not implemented: ChargingTraceByID - chargingTraceById"))
}
