package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"go-ocs/internal/backend/graphql/model"
)

// CreateCarrier is the resolver for the createCarrier field.
func (r *mutationResolver) CreateCarrier(ctx context.Context, carrier model.CarrierInput) (*model.Carrier, error) {
	return r.CarrierSvc.CreateCarrier(ctx, carrier)
}

// UpdateCarrier is the resolver for the updateCarrier field.
func (r *mutationResolver) UpdateCarrier(ctx context.Context, plmn string, carrier model.CarrierInput) (*model.Carrier, error) {
	return r.CarrierSvc.UpdateCarrier(ctx, plmn, carrier)
}

// DeleteCarrier is the resolver for the deleteCarrier field.
func (r *mutationResolver) DeleteCarrier(ctx context.Context, plmn string) (bool, error) {
	return r.CarrierSvc.DeleteCarrier(ctx, plmn)
}

// CarrierList is the resolver for the carrierList field.
func (r *queryResolver) CarrierList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.Carrier, error) {
	return r.CarrierSvc.ListCarriers(ctx, page, filter)
}

// CarrierByPlmn is the resolver for the carrierByPlmn field.
func (r *queryResolver) CarrierByPlmn(ctx context.Context, plmn string) (*model.Carrier, error) {
	return r.CarrierSvc.CarrierByPlmn(ctx, plmn)
}

// CountCarriers is the resolver for the countCarriers field.
func (r *queryResolver) CountCarriers(ctx context.Context, filter *model.FilterRequest) (int, error) {
	return r.CarrierSvc.CountCarriers(ctx, filter)
}
