package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"go-ocs/internal/backend/graphql/model"
)

// CreateClassification is the resolver for the createClassification field.
func (r *mutationResolver) CreateClassification(ctx context.Context, classification model.ClassificationInput) (*model.Classification, error) {
	return r.ClassificationSvc.CreateClassification(ctx, classification)
}

// CloneClassification is the resolver for the cloneClassification field.
func (r *mutationResolver) CloneClassification(ctx context.Context, classificationID string) (*model.Classification, error) {
	return r.ClassificationSvc.CloneClassification(ctx, classificationID)
}

// UpdateClassificationPlan is the resolver for the updateClassificationPlan field.
func (r *mutationResolver) UpdateClassificationPlan(ctx context.Context, classificationID string, classification model.ClassificationInput) (*model.Classification, error) {
	return r.ClassificationSvc.UpdateClassificationPlan(ctx, classificationID, classification)
}

// SubmitClassificationForApproval is the resolver for the submitClassificationForApproval field.
func (r *mutationResolver) SubmitClassificationForApproval(ctx context.Context, classificationID string) (*model.Classification, error) {
	return r.ClassificationSvc.SubmitClassificationForApproval(ctx, classificationID)
}

// ApproveClassificationPlan is the resolver for the approveClassificationPlan field.
func (r *mutationResolver) ApproveClassificationPlan(ctx context.Context, classificationID string) (*model.Classification, error) {
	return r.ClassificationSvc.ApproveClassificationPlan(ctx, classificationID)
}

// DeclineClassificationPlan is the resolver for the declineClassificationPlan field.
func (r *mutationResolver) DeclineClassificationPlan(ctx context.Context, classificationID string) (*model.Classification, error) {
	return r.ClassificationSvc.DeclineClassificationPlan(ctx, classificationID)
}

// DeleteClassification is the resolver for the deleteClassification field.
func (r *mutationResolver) DeleteClassification(ctx context.Context, classificationID string) (bool, error) {
	return r.ClassificationSvc.DeleteClassification(ctx, classificationID)
}

// ClassificationList is the resolver for the classificationList field.
func (r *queryResolver) ClassificationList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.Classification, error) {
	return r.ClassificationSvc.ListClassifications(ctx, page, filter)
}

// CountClassifications is the resolver for the countClassifications field.
func (r *queryResolver) CountClassifications(ctx context.Context, filter *model.FilterRequest) (int, error) {
	return r.ClassificationSvc.CountClassifications(ctx, filter)
}

// RateKeyInput is the resolver for the rateKeyInput field.
func (r *queryResolver) RateKeyInput(ctx context.Context) (*model.RateKeyInput, error) {
	return r.ClassificationSvc.RateKeyInput(ctx)
}

// Classification is the resolver for the classification field.
func (r *queryResolver) Classification(ctx context.Context, classificationID string) (*model.Classification, error) {
	return r.ClassificationSvc.GetClassification(ctx, classificationID)
}
