package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"go-ocs/internal/backend/graphql/model"
)

// CreateDestinationGroup is the resolver for the createDestinationGroup field.
func (r *mutationResolver) CreateDestinationGroup(ctx context.Context, destinationGroup model.DestinationGroupInput) (*model.DestinationGroup, error) {
	panic(fmt.Errorf("not implemented: CreateDestinationGroup - createDestinationGroup"))
}

// UpdateDestinationGroup is the resolver for the updateDestinationGroup field.
func (r *mutationResolver) UpdateDestinationGroup(ctx context.Context, groupName string, destinationGroup model.DestinationGroupInput) (*model.DestinationGroup, error) {
	panic(fmt.Errorf("not implemented: UpdateDestinationGroup - updateDestinationGroup"))
}

// DeleteDestinationGroup is the resolver for the deleteDestinationGroup field.
func (r *mutationResolver) DeleteDestinationGroup(ctx context.Context, groupName string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDestinationGroup - deleteDestinationGroup"))
}

// DestinationGroupList is the resolver for the destinationGroupList field.
func (r *queryResolver) DestinationGroupList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.DestinationGroup, error) {
	panic(fmt.Errorf("not implemented: DestinationGroupList - destinationGroupList"))
}

// CountDestinationGroup is the resolver for the countDestinationGroup field.
func (r *queryResolver) CountDestinationGroup(ctx context.Context, filter *model.FilterRequest) (int, error) {
	panic(fmt.Errorf("not implemented: CountDestinationGroup - countDestinationGroup"))
}

// DestinationGroupByGroupName is the resolver for the destinationGroupByGroupName field.
func (r *queryResolver) DestinationGroupByGroupName(ctx context.Context, groupName string) (*model.DestinationGroup, error) {
	panic(fmt.Errorf("not implemented: DestinationGroupByGroupName - destinationGroupByGroupName"))
}
