package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"go-ocs/internal/backend/graphql/model"
)

// CreateNumberPlan is the resolver for the createNumberPlan field.
func (r *mutationResolver) CreateNumberPlan(ctx context.Context, numberPlan model.NumberPlanInput) (*model.NumberPlan, error) {
	return r.NumberPlanSvc.CreateNumberPlan(ctx, numberPlan)
}

// UpdateNumberPlan is the resolver for the updateNumberPlan field.
func (r *mutationResolver) UpdateNumberPlan(ctx context.Context, numberID string, numberPlan model.NumberPlanInput) (*model.NumberPlan, error) {
	return r.NumberPlanSvc.UpdateNumberPlan(ctx, numberID, numberPlan)
}

// DeleteNumberPlan is the resolver for the deleteNumberPlan field.
func (r *mutationResolver) DeleteNumberPlan(ctx context.Context, numberID string) (bool, error) {
	return r.NumberPlanSvc.DeleteNumberPlan(ctx, numberID)
}

// NumberPlanList is the resolver for the numberPlanList field.
func (r *queryResolver) NumberPlanList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.NumberPlan, error) {
	return r.NumberPlanSvc.ListNumberPlans(ctx, page, filter)
}

// CountNumberPlans is the resolver for the countNumberPlans field.
func (r *queryResolver) CountNumberPlans(ctx context.Context, filter *model.FilterRequest) (int, error) {
	return r.NumberPlanSvc.CountNumberPlans(ctx, filter)
}

// NumberPlan is the resolver for the numberPlan field.
func (r *queryResolver) NumberPlan(ctx context.Context, numberID string) (*model.NumberPlan, error) {
	return r.NumberPlanSvc.GetNumberPlan(ctx, numberID)
}
