package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"time"

	"go-ocs/internal/backend/graphql/model"
)

// CancelQuotaReservations is the resolver for the cancelQuotaReservations field.
func (r *mutationResolver) CancelQuotaReservations(ctx context.Context, reservationID string, subscriberID string) (*model.QuotaOperationResponse, error) {
	return r.QuotaSvc.CancelReservations(ctx, reservationID, subscriberID)
}

// ReserveQuota is the resolver for the reserveQuota field.
func (r *mutationResolver) ReserveQuota(ctx context.Context, reservationID string, subscriberID string, reasonCode model.ReasonCode, rateKey model.QuotaRateKeyInput, unitType model.UnitType, requestedUnits int, unitPrice string, validitySeconds int, allowOOBCharging bool) (*model.QuotaReserveResponse, error) {
	return r.QuotaSvc.ReserveQuota(ctx, time.Now().UTC(), reservationID, subscriberID, reasonCode, rateKey, unitType, requestedUnits, unitPrice, validitySeconds, allowOOBCharging)
}

// DebitQuota is the resolver for the debitQuota field.
func (r *mutationResolver) DebitQuota(ctx context.Context, subscriberID string, reservationID string, usedUnits int, unitType model.UnitType, reclaimUnusedUnits bool) (*model.QuotaDebitResponse, error) {
	return r.QuotaSvc.DebitQuota(ctx, time.Now().UTC(), subscriberID, reservationID, usedUnits, unitType, reclaimUnusedUnits)
}

// QuotaBalance is the resolver for the quotaBalance field.
func (r *queryResolver) QuotaBalance(ctx context.Context, balanceEnquiryRequest model.QuotaBalanceRequestInput) (*model.QuotaBalanceResponse, error) {
	return r.QuotaSvc.GetBalance(ctx, time.Now().UTC(), balanceEnquiryRequest)
}

// QuotaBalances is the resolver for the quotaBalances field.
func (r *queryResolver) QuotaBalances(ctx context.Context, balanceEnquiryRequest model.QuotaBalanceRequestInput) ([]*model.QuotaBalanceResponse, error) {
	return r.QuotaSvc.GetBalances(ctx, time.Now().UTC(), balanceEnquiryRequest)
}
