package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"go-ocs/internal/backend/graphql/model"
)

// CreateRatePlan is the resolver for the createRatePlan field.
func (r *mutationResolver) CreateRatePlan(ctx context.Context, ratePlan model.RatePlanInput) (*model.RatePlan, error) {
	return r.RatePlanSvc.CreateRatePlan(ctx, ratePlan)
}

// UpdateRatePlan is the resolver for the updateRatePlan field.
func (r *mutationResolver) UpdateRatePlan(ctx context.Context, planID string, ratePlan model.RatePlanInput) (*model.RatePlan, error) {
	return r.RatePlanSvc.UpdateRatePlan(ctx, planID, ratePlan)
}

// UpdateRatePlanRules is the resolver for the updateRatePlanRules field.
func (r *mutationResolver) UpdateRatePlanRules(ctx context.Context, planID string, rateLines []*model.RateLineInput) (*model.RatePlan, error) {
	return r.RatePlanSvc.UpdateRatePlanRules(ctx, planID, rateLines)
}

// CloneRatePlan is the resolver for the cloneRatePlan field.
func (r *mutationResolver) CloneRatePlan(ctx context.Context, planID string) (*model.RatePlan, error) {
	return r.RatePlanSvc.CloneRatePlan(ctx, planID)
}

// SubmitRatePlanForApproval is the resolver for the submitRatePlanForApproval field.
func (r *mutationResolver) SubmitRatePlanForApproval(ctx context.Context, planID string) (*model.RatePlan, error) {
	return r.RatePlanSvc.SubmitRatePlanForApproval(ctx, planID)
}

// ApproveRatePlan is the resolver for the approveRatePlan field.
func (r *mutationResolver) ApproveRatePlan(ctx context.Context, planID string) (*model.RatePlan, error) {
	return r.RatePlanSvc.ApproveRatePlan(ctx, planID)
}

// DeclineRatePlan is the resolver for the declineRatePlan field.
func (r *mutationResolver) DeclineRatePlan(ctx context.Context, planID string) (*model.RatePlan, error) {
	return r.RatePlanSvc.DeclineRatePlan(ctx, planID)
}

// DeleteRatePlan is the resolver for the deleteRatePlan field.
func (r *mutationResolver) DeleteRatePlan(ctx context.Context, planID string) (bool, error) {
	return r.RatePlanSvc.DeleteRatePlan(ctx, planID)
}

// RatePlanList is the resolver for the ratePlanList field.
func (r *queryResolver) RatePlanList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.RatePlan, error) {
	return r.RatePlanSvc.ListRatePlans(ctx, page, filter)
}

// CountRatePlans is the resolver for the countRatePlans field.
func (r *queryResolver) CountRatePlans(ctx context.Context, filter *model.FilterRequest) (int, error) {
	return r.RatePlanSvc.CountRatePlans(ctx, filter)
}

// RatePlan is the resolver for the ratePlan field.
func (r *queryResolver) RatePlan(ctx context.Context, planID string) (*model.RatePlan, error) {
	return r.RatePlanSvc.GetRatePlan(ctx, planID)
}

// LatestRatePlanList is the resolver for the latestRatePlanList field.
func (r *queryResolver) LatestRatePlanList(ctx context.Context, planType model.RatePlanType) ([]*model.RatePlan, error) {
	return r.RatePlanSvc.LatestRatePlanList(ctx, planType)
}
