package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"go-ocs/internal/backend/graphql/model"
)

// CreateSourceGroup is the resolver for the createSourceGroup field.
func (r *mutationResolver) CreateSourceGroup(ctx context.Context, sourceGroup model.SourceGroupInput) (*model.SourceGroup, error) {
	panic(fmt.Errorf("not implemented: CreateSourceGroup - createSourceGroup"))
}

// UpdateSourceGroup is the resolver for the updateSourceGroup field.
func (r *mutationResolver) UpdateSourceGroup(ctx context.Context, groupName string, sourceGroup model.SourceGroupInput) (*model.SourceGroup, error) {
	panic(fmt.Errorf("not implemented: UpdateSourceGroup - updateSourceGroup"))
}

// DeleteSourceGroup is the resolver for the deleteSourceGroup field.
func (r *mutationResolver) DeleteSourceGroup(ctx context.Context, groupName string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSourceGroup - deleteSourceGroup"))
}

// SourceGroupList is the resolver for the sourceGroupList field.
func (r *queryResolver) SourceGroupList(ctx context.Context, page *model.PageRequest, filter *model.FilterRequest) ([]*model.SourceGroup, error) {
	panic(fmt.Errorf("not implemented: SourceGroupList - sourceGroupList"))
}

// CountSourceGroup is the resolver for the countSourceGroup field.
func (r *queryResolver) CountSourceGroup(ctx context.Context, filter *model.FilterRequest) (int, error) {
	panic(fmt.Errorf("not implemented: CountSourceGroup - countSourceGroup"))
}

// SourceGroupByGroupName is the resolver for the sourceGroupByGroupName field.
func (r *queryResolver) SourceGroupByGroupName(ctx context.Context, groupName string) (*model.SourceGroup, error) {
	panic(fmt.Errorf("not implemented: SourceGroupByGroupName - sourceGroupByGroupName"))
}
