// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AdminUser struct {
	ID        string   `json:"id"`
	Username  string   `json:"username"`
	Email     *string  `json:"email,omitempty"`
	FirstName *string  `json:"firstName,omitempty"`
	LastName  *string  `json:"lastName,omitempty"`
	Roles     []string `json:"roles"`
}

type Carrier struct {
	Plmn             string  `json:"plmn"`
	Mcc              string  `json:"mcc"`
	Mnc              *string `json:"mnc,omitempty"`
	CarrierName      string  `json:"carrierName"`
	SourceGroup      string  `json:"sourceGroup"`
	DestinationGroup string  `json:"destinationGroup"`
	CountryName      string  `json:"countryName"`
	Iso              string  `json:"iso"`
	ModifiedOn       *string `json:"modifiedOn,omitempty"`
}

type CarrierInput struct {
	Plmn             string  `json:"plmn"`
	Mcc              string  `json:"mcc"`
	Mnc              *string `json:"mnc,omitempty"`
	CarrierName      string  `json:"carrierName"`
	SourceGroup      string  `json:"sourceGroup"`
	DestinationGroup string  `json:"destinationGroup"`
	CountryName      string  `json:"countryName"`
	Iso              string  `json:"iso"`
}

type Classification struct {
	ClassificationID string               `json:"classificationId"`
	Name             string               `json:"name"`
	CreatedOn        *string              `json:"createdOn,omitempty"`
	EffectiveTime    string               `json:"effectiveTime"`
	CreatedBy        string               `json:"createdBy"`
	ApprovedBy       *string              `json:"approvedBy,omitempty"`
	Status           ClassificationStatus `json:"status"`
	Plan             *ClassificationPlan  `json:"plan"`
}

type ClassificationInput struct {
	Name          string                   `json:"name"`
	EffectiveTime string                   `json:"effectiveTime"`
	Plan          *ClassificationPlanInput `json:"plan"`
}

type ClassificationPlan struct {
	RuleSetID            *string                      `json:"ruleSetId,omitempty"`
	RuleSetName          *string                      `json:"ruleSetName,omitempty"`
	UseServiceWindows    bool                         `json:"useServiceWindows"`
	DefaultServiceWindow string                       `json:"defaultServiceWindow"`
	DefaultSourceType    string                       `json:"defaultSourceType"`
	ServiceWindows       []*ServiceWindowEntry        `json:"serviceWindows,omitempty"`
	ServiceTypes         []*ClassificationServiceType `json:"serviceTypes,omitempty"`
}

type ClassificationPlanInput struct {
	RuleSetID            *string                           `json:"ruleSetId,omitempty"`
	RuleSetName          *string                           `json:"ruleSetName,omitempty"`
	UseServiceWindows    bool                              `json:"useServiceWindows"`
	DefaultServiceWindow string                            `json:"defaultServiceWindow"`
	DefaultSourceType    string                            `json:"defaultSourceType"`
	ServiceWindows       []*ServiceWindowEntryInput        `json:"serviceWindows,omitempty"`
	ServiceTypes         []*ClassificationServiceTypeInput `json:"serviceTypes"`
}

type ClassificationServiceType struct {
	Type                   string                     `json:"type"`
	ChargingInformation    string                     `json:"chargingInformation"`
	ServiceTypeRule        *string                    `json:"serviceTypeRule,omitempty"`
	Description            *string                    `json:"description,omitempty"`
	SourceType             string                     `json:"sourceType"`
	ServiceDirection       string                     `json:"serviceDirection"`
	ServiceCategory        string                     `json:"serviceCategory"`
	ServiceIdentifier      *string                    `json:"serviceIdentifier,omitempty"`
	DefaultServiceCategory *string                    `json:"defaultServiceCategory,omitempty"`
	UnitType               string                     `json:"unitType"`
	ServiceWindows         []string                   `json:"serviceWindows,omitempty"`
	ServiceCategoryMap     []*ServiceCategoryMapEntry `json:"serviceCategoryMap,omitempty"`
}

type ClassificationServiceTypeInput struct {
	Type                   string                          `json:"type"`
	ChargingInformation    string                          `json:"chargingInformation"`
	ServiceTypeRule        *string                         `json:"serviceTypeRule,omitempty"`
	Description            *string                         `json:"description,omitempty"`
	SourceType             string                          `json:"sourceType"`
	ServiceDirection       string                          `json:"serviceDirection"`
	ServiceCategory        string                          `json:"serviceCategory"`
	ServiceIdentifier      *string                         `json:"serviceIdentifier,omitempty"`
	DefaultServiceCategory *string                         `json:"defaultServiceCategory,omitempty"`
	UnitType               string                          `json:"unitType"`
	ServiceWindows         []string                        `json:"serviceWindows,omitempty"`
	ServiceCategoryMap     []*ServiceCategoryMapEntryInput `json:"serviceCategoryMap,omitempty"`
}

type FilterInput struct {
	Key       string `json:"key"`
	Operation string `json:"operation"`
	Value     string `json:"value"`
}

type FilterRequest struct {
	Filters  []*FilterInput `json:"filters,omitempty"`
	Wildcard *string        `json:"wildcard,omitempty"`
}

type LookupData struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NumberPlan struct {
	NumberID     string  `json:"numberId"`
	Name         string  `json:"name"`
	Plmn         string  `json:"plmn"`
	NumberRange  string  `json:"numberRange"`
	NumberLength int     `json:"numberLength"`
	ModifiedOn   *string `json:"modifiedOn,omitempty"`
}

type NumberPlanInput struct {
	Name         *string `json:"name,omitempty"`
	Plmn         string  `json:"plmn"`
	NumberRange  string  `json:"numberRange"`
	NumberLength int     `json:"numberLength"`
}

type PageRequest struct {
	PageIndex *int       `json:"pageIndex,omitempty"`
	PageSize  *int       `json:"pageSize,omitempty"`
	Sort      *SortInput `json:"sort,omitempty"`
}

type Query struct {
}

type QuotaBalanceRequestInput struct {
	SubscriberID string      `json:"subscriberId"`
	UnitType     *UnitType   `json:"unitType,omitempty"`
	BalanceType  BalanceType `json:"balanceType"`
}

type QuotaBalanceResponse struct {
	UnitType         UnitType `json:"unitType"`
	TotalValue       string   `json:"totalValue"`
	AvailableBalance string   `json:"availableBalance"`
}

type QuotaDebitResponse struct {
	UnitsDebited     int    `json:"unitsDebited"`
	UnitsValue       string `json:"unitsValue"`
	ValueUnits       int    `json:"valueUnits"`
	UnaccountedUnits int    `json:"unaccountedUnits"`
}

type QuotaOperationResponse struct {
	Success bool `json:"success"`
}

type QuotaRateKeyInput struct {
	ServiceType      string  `json:"serviceType"`
	SourceType       string  `json:"sourceType"`
	ServiceDirection string  `json:"serviceDirection"`
	ServiceCategory  string  `json:"serviceCategory"`
	ServiceWindow    *string `json:"serviceWindow,omitempty"`
}

type QuotaReserveResponse struct {
	GrantedUnits int `json:"grantedUnits"`
}

type RateKeyInput struct {
	ServiceTypes      []*LookupData            `json:"serviceTypes"`
	SourceTypes       []*LookupData            `json:"sourceTypes"`
	ServiceDirections []*LookupData            `json:"serviceDirections"`
	ServiceCategories []*ServiceCategoryLookup `json:"serviceCategories"`
	ServiceWindows    []*ServiceCategoryLookup `json:"serviceWindows"`
}

type RateLine struct {
	ClassificationKey string  `json:"classificationKey"`
	GroupKey          *string `json:"groupKey,omitempty"`
	Description       *string `json:"description,omitempty"`
	TariffType        string  `json:"tariffType"`
	UnitType          string  `json:"unitType"`
	BaseTariff        string  `json:"baseTariff"`
	UnitOfMeasure     int     `json:"unitOfMeasure"`
	Multiplier        string  `json:"multiplier"`
	QosProfile        *string `json:"qosProfile,omitempty"`
	MinimumUnits      int     `json:"minimumUnits"`
	RoundingIncrement int     `json:"roundingIncrement"`
	Barred            bool    `json:"barred"`
	MonetaryOnly      bool    `json:"monetaryOnly"`
}

type RateLineInput struct {
	ClassificationKey string  `json:"classificationKey"`
	GroupKey          *string `json:"groupKey,omitempty"`
	Description       *string `json:"description,omitempty"`
	TariffType        string  `json:"tariffType"`
	UnitType          string  `json:"unitType"`
	BaseTariff        string  `json:"baseTariff"`
	UnitOfMeasure     int     `json:"unitOfMeasure"`
	Multiplier        string  `json:"multiplier"`
	QosProfile        *string `json:"qosProfile,omitempty"`
	MinimumUnits      int     `json:"minimumUnits"`
	RoundingIncrement int     `json:"roundingIncrement"`
	Barred            bool    `json:"barred"`
	MonetaryOnly      bool    `json:"monetaryOnly"`
}

type RatePlan struct {
	PlanID      string         `json:"planId"`
	PlanName    string         `json:"planName"`
	PlanType    RatePlanType   `json:"planType"`
	WholesaleID *string        `json:"wholesaleId,omitempty"`
	PlanStatus  RatePlanStatus `json:"planStatus"`
	CreatedBy   string         `json:"createdBy"`
	ApprovedBy  *string        `json:"approvedBy,omitempty"`
	EffectiveAt string         `json:"effectiveAt"`
	ModifiedAt  *string        `json:"modifiedAt,omitempty"`
	RateLines   []*RateLine    `json:"rateLines"`
}

type RatePlanInput struct {
	PlanName    string           `json:"planName"`
	PlanType    RatePlanType     `json:"planType"`
	EffectiveAt string           `json:"effectiveAt"`
	RateLines   []*RateLineInput `json:"rateLines"`
}

type ServiceCategoryLookup struct {
	Code            string `json:"code"`
	Name            string `json:"name"`
	ServiceTypeCode string `json:"serviceTypeCode"`
}

type ServiceCategoryMapEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ServiceCategoryMapEntryInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ServiceWindowEntry struct {
	Name      string `json:"name"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type ServiceWindowEntryInput struct {
	Name      string `json:"name"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type SortInput struct {
	Key   string `json:"key"`
	Order string `json:"order"`
}

type BalanceType string

const (
	BalanceTypeAvailableBalance    BalanceType = "AVAILABLE_BALANCE"
	BalanceTypeTransferableBalance BalanceType = "TRANSFERABLE_BALANCE"
	BalanceTypeConvertableBalance  BalanceType = "CONVERTABLE_BALANCE"
)

var AllBalanceType = []BalanceType{
	BalanceTypeAvailableBalance,
	BalanceTypeTransferableBalance,
	BalanceTypeConvertableBalance,
}

func (e BalanceType) IsValid() bool {
	switch e {
	case BalanceTypeAvailableBalance, BalanceTypeTransferableBalance, BalanceTypeConvertableBalance:
		return true
	}
	return false
}

func (e BalanceType) String() string {
	return string(e)
}

func (e *BalanceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BalanceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BalanceType", str)
	}
	return nil
}

func (e BalanceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BalanceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BalanceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ClassificationStatus string

const (
	ClassificationStatusDraft   ClassificationStatus = "DRAFT"
	ClassificationStatusPending ClassificationStatus = "PENDING"
	ClassificationStatusActive  ClassificationStatus = "ACTIVE"
	ClassificationStatusRetired ClassificationStatus = "RETIRED"
)

var AllClassificationStatus = []ClassificationStatus{
	ClassificationStatusDraft,
	ClassificationStatusPending,
	ClassificationStatusActive,
	ClassificationStatusRetired,
}

func (e ClassificationStatus) IsValid() bool {
	switch e {
	case ClassificationStatusDraft, ClassificationStatusPending, ClassificationStatusActive, ClassificationStatusRetired:
		return true
	}
	return false
}

func (e ClassificationStatus) String() string {
	return string(e)
}

func (e *ClassificationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClassificationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClassificationStatus", str)
	}
	return nil
}

func (e ClassificationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ClassificationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ClassificationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RatePlanStatus string

const (
	RatePlanStatusDraft   RatePlanStatus = "DRAFT"
	RatePlanStatusPending RatePlanStatus = "PENDING"
	RatePlanStatusActive  RatePlanStatus = "ACTIVE"
	RatePlanStatusRetired RatePlanStatus = "RETIRED"
)

var AllRatePlanStatus = []RatePlanStatus{
	RatePlanStatusDraft,
	RatePlanStatusPending,
	RatePlanStatusActive,
	RatePlanStatusRetired,
}

func (e RatePlanStatus) IsValid() bool {
	switch e {
	case RatePlanStatusDraft, RatePlanStatusPending, RatePlanStatusActive, RatePlanStatusRetired:
		return true
	}
	return false
}

func (e RatePlanStatus) String() string {
	return string(e)
}

func (e *RatePlanStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RatePlanStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RatePlanStatus", str)
	}
	return nil
}

func (e RatePlanStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RatePlanStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RatePlanStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RatePlanType string

const (
	RatePlanTypeSettlement RatePlanType = "SETTLEMENT"
	RatePlanTypeWholesale  RatePlanType = "WHOLESALE"
	RatePlanTypeRetail     RatePlanType = "RETAIL"
)

var AllRatePlanType = []RatePlanType{
	RatePlanTypeSettlement,
	RatePlanTypeWholesale,
	RatePlanTypeRetail,
}

func (e RatePlanType) IsValid() bool {
	switch e {
	case RatePlanTypeSettlement, RatePlanTypeWholesale, RatePlanTypeRetail:
		return true
	}
	return false
}

func (e RatePlanType) String() string {
	return string(e)
}

func (e *RatePlanType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RatePlanType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RatePlanType", str)
	}
	return nil
}

func (e RatePlanType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RatePlanType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RatePlanType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReasonCode string

const (
	ReasonCodeQuotaProvisioned ReasonCode = "QUOTA_PROVISIONED"
	ReasonCodeServiceUsage     ReasonCode = "SERVICE_USAGE"
	ReasonCodeConversion       ReasonCode = "CONVERSION"
	ReasonCodeTransferIn       ReasonCode = "TRANSFER_IN"
	ReasonCodeTransferOut      ReasonCode = "TRANSFER_OUT"
	ReasonCodeLoanRepayment    ReasonCode = "LOAN_REPAYMENT"
	ReasonCodeTransactionFee   ReasonCode = "TRANSACTION_FEE"
	ReasonCodeQuotaExpiry      ReasonCode = "QUOTA_EXPIRY"
)

var AllReasonCode = []ReasonCode{
	ReasonCodeQuotaProvisioned,
	ReasonCodeServiceUsage,
	ReasonCodeConversion,
	ReasonCodeTransferIn,
	ReasonCodeTransferOut,
	ReasonCodeLoanRepayment,
	ReasonCodeTransactionFee,
	ReasonCodeQuotaExpiry,
}

func (e ReasonCode) IsValid() bool {
	switch e {
	case ReasonCodeQuotaProvisioned, ReasonCodeServiceUsage, ReasonCodeConversion, ReasonCodeTransferIn, ReasonCodeTransferOut, ReasonCodeLoanRepayment, ReasonCodeTransactionFee, ReasonCodeQuotaExpiry:
		return true
	}
	return false
}

func (e ReasonCode) String() string {
	return string(e)
}

func (e *ReasonCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReasonCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReasonCode", str)
	}
	return nil
}

func (e ReasonCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReasonCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReasonCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UnitType string

const (
	UnitTypeSeconds  UnitType = "SECONDS"
	UnitTypeOctets   UnitType = "OCTETS"
	UnitTypeUnits    UnitType = "UNITS"
	UnitTypeMonetary UnitType = "MONETARY"
)

var AllUnitType = []UnitType{
	UnitTypeSeconds,
	UnitTypeOctets,
	UnitTypeUnits,
	UnitTypeMonetary,
}

func (e UnitType) IsValid() bool {
	switch e {
	case UnitTypeSeconds, UnitTypeOctets, UnitTypeUnits, UnitTypeMonetary:
		return true
	}
	return false
}

func (e UnitType) String() string {
	return string(e)
}

func (e *UnitType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UnitType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UnitType", str)
	}
	return nil
}

func (e UnitType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UnitType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UnitType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
