// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminUser struct {
	ID        string   `json:"id"`
	Username  string   `json:"username"`
	Email     *string  `json:"email,omitempty"`
	FirstName *string  `json:"firstName,omitempty"`
	LastName  *string  `json:"lastName,omitempty"`
	Roles     []string `json:"roles"`
}

type Carrier struct {
	Plmn             string  `json:"plmn"`
	Mcc              string  `json:"mcc"`
	Mnc              *string `json:"mnc,omitempty"`
	CarrierName      string  `json:"carrierName"`
	SourceGroup      string  `json:"sourceGroup"`
	DestinationGroup string  `json:"destinationGroup"`
	CountryName      string  `json:"countryName"`
	Iso              string  `json:"iso"`
	ModifiedOn       *string `json:"modifiedOn,omitempty"`
}

type CarrierInput struct {
	Plmn             string  `json:"plmn"`
	Mcc              string  `json:"mcc"`
	Mnc              *string `json:"mnc,omitempty"`
	CarrierName      string  `json:"carrierName"`
	SourceGroup      string  `json:"sourceGroup"`
	DestinationGroup string  `json:"destinationGroup"`
	CountryName      string  `json:"countryName"`
	Iso              string  `json:"iso"`
}

type FilterInput struct {
	Key       string `json:"key"`
	Operation string `json:"operation"`
	Value     string `json:"value"`
}

type FilterRequest struct {
	Filters  []*FilterInput `json:"filters,omitempty"`
	Wildcard *string        `json:"wildcard,omitempty"`
}

type Mutation struct {
}

type PageRequest struct {
	PageIndex *int       `json:"pageIndex,omitempty"`
	PageSize  *int       `json:"pageSize,omitempty"`
	Sort      *SortInput `json:"sort,omitempty"`
}

type Query struct {
}

type SortInput struct {
	Key   string `json:"key"`
	Order string `json:"order"`
}
