// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carrriers.sql

package sqlc

import (
	"context"
)

const allCarriers = `-- name: AllCarriers :many
select plmn, modified_on, mcc, mnc, carrier_name, source_group, destination_group, country_name, iso
from carrier
order by plmn
`

func (q *Queries) AllCarriers(ctx context.Context) ([]Carrier, error) {
	rows, err := q.db.Query(ctx, allCarriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Carrier
	for rows.Next() {
		var i Carrier
		if err := rows.Scan(
			&i.Plmn,
			&i.ModifiedOn,
			&i.Mcc,
			&i.Mnc,
			&i.CarrierName,
			&i.SourceGroup,
			&i.DestinationGroup,
			&i.CountryName,
			&i.Iso,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
