// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charging_trace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChargingTrace = `-- name: CreateChargingTrace :one
insert into charging_trace(trace_id, charging_id, sequence_nr, created_at, request, response, execution_time, msisdn)
values (gen_random_uuid(), $1, $2, now(), $3, $4, $5, $6)
returning trace_id
`

type CreateChargingTraceParams struct {
	ChargingID    string
	SequenceNr    int32
	Request       []byte
	Response      []byte
	ExecutionTime int64
	Msisdn        string
}

func (q *Queries) CreateChargingTrace(ctx context.Context, arg CreateChargingTraceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createChargingTrace,
		arg.ChargingID,
		arg.SequenceNr,
		arg.Request,
		arg.Response,
		arg.ExecutionTime,
		arg.Msisdn,
	)
	var trace_id pgtype.UUID
	err := row.Scan(&trace_id)
	return trace_id, err
}

const deleteOldChargingTrace = `-- name: DeleteOldChargingTrace :execrows
DELETE FROM charging_trace
WHERE created_at < $1
`

// Deletes all charging_trace rows whose created_at is before the given threshold.
// Used by the housekeeping job to purge old audit trail records.
func (q *Queries) DeleteOldChargingTrace(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldChargingTrace, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findChargingTraceByIdSeqNr = `-- name: FindChargingTraceByIdSeqNr :one
select trace_id,
       created_at,
       request,
       response,
       execution_time,
       charging_id,
       sequence_nr,
       msisdn

from charging_trace
where charging_id = $1
  and sequence_nr = $2
`

func (q *Queries) FindChargingTraceByIdSeqNr(ctx context.Context, chargingID string, sequenceNr int32) (ChargingTrace, error) {
	row := q.db.QueryRow(ctx, findChargingTraceByIdSeqNr, chargingID, sequenceNr)
	var i ChargingTrace
	err := row.Scan(
		&i.TraceID,
		&i.CreatedAt,
		&i.Request,
		&i.Response,
		&i.ExecutionTime,
		&i.ChargingID,
		&i.SequenceNr,
		&i.Msisdn,
	)
	return i, err
}

const findChargingTraceByTraceId = `-- name: FindChargingTraceByTraceId :one
SELECT trace_id,
       created_at,
       request,
       response,
       execution_time,
       charging_id,
       sequence_nr,
       msisdn
FROM charging_trace
WHERE trace_id = $1
`

func (q *Queries) FindChargingTraceByTraceId(ctx context.Context, traceID pgtype.UUID) (ChargingTrace, error) {
	row := q.db.QueryRow(ctx, findChargingTraceByTraceId, traceID)
	var i ChargingTrace
	err := row.Scan(
		&i.TraceID,
		&i.CreatedAt,
		&i.Request,
		&i.Response,
		&i.ExecutionTime,
		&i.ChargingID,
		&i.SequenceNr,
		&i.Msisdn,
	)
	return i, err
}
