// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: charging_data.sql

package sqlc

import (
	"context"
)

const createChargeData = `-- name: CreateChargeData :exec
insert into charging_data(charging_id, sequence_number, charge_data)
values ($1, $2, $3)
`

func (q *Queries) CreateChargeData(ctx context.Context, chargingID string, sequenceNumber int64, chargeData []byte) error {
	_, err := q.db.Exec(ctx, createChargeData, chargingID, sequenceNumber, chargeData)
	return err
}

const deleteChargeDate = `-- name: DeleteChargeDate :exec
delete
from charging_data
where charging_id = $1
`

func (q *Queries) DeleteChargeDate(ctx context.Context, chargingID string) error {
	_, err := q.db.Exec(ctx, deleteChargeDate, chargingID)
	return err
}

const getChargingDataByChargeId = `-- name: GetChargingDataByChargeId :one
select charging_id,
       sequence_number,
       modified_on,
       charge_data
from charging_data
where charging_id = $1
`

func (q *Queries) GetChargingDataByChargeId(ctx context.Context, chargingID string) (ChargingDatum, error) {
	row := q.db.QueryRow(ctx, getChargingDataByChargeId, chargingID)
	var i ChargingDatum
	err := row.Scan(
		&i.ChargingID,
		&i.SequenceNumber,
		&i.ModifiedOn,
		&i.ChargeData,
	)
	return i, err
}

const updateChargeData = `-- name: UpdateChargeData :exec
UPDATE charging_data
set sequence_number = $2,
    charge_data = $3,
    modified_on=now()
where charging_id = $1
`

func (q *Queries) UpdateChargeData(ctx context.Context, chargingID string, sequenceNumber int64, chargeData []byte) error {
	_, err := q.db.Exec(ctx, updateChargeData, chargingID, sequenceNumber, chargeData)
	return err
}
