// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveClassification = `-- name: ApproveClassification :one
UPDATE classification
SET status      = 'ACTIVE',
    approved_by = $2
WHERE classification_id = $1
  AND status = 'PENDING'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan
`

// Transitions a PENDING classification to ACTIVE and records the approver.
func (q *Queries) ApproveClassification(ctx context.Context, classificationID pgtype.UUID, approvedBy pgtype.Text) (Classification, error) {
	row := q.db.QueryRow(ctx, approveClassification, classificationID, approvedBy)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const createClassification = `-- name: CreateClassification :one
INSERT INTO classification (classification_id, name, effective_time, created_by, plan, status)
VALUES ($1, $2, $3, $4, $5, 'DRAFT')
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan
`

type CreateClassificationParams struct {
	ClassificationID pgtype.UUID
	Name             string
	EffectiveTime    pgtype.Timestamptz
	CreatedBy        string
	Plan             []byte
}

// Inserts a new classification in DRAFT status and returns the full persisted row.
// classification_id is generated by the application (uuid.New()).
func (q *Queries) CreateClassification(ctx context.Context, arg CreateClassificationParams) (Classification, error) {
	row := q.db.QueryRow(ctx, createClassification,
		arg.ClassificationID,
		arg.Name,
		arg.EffectiveTime,
		arg.CreatedBy,
		arg.Plan,
	)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const declineClassification = `-- name: DeclineClassification :one
UPDATE classification
SET status      = 'DRAFT',
    approved_by = NULL
WHERE classification_id = $1
  AND status = 'PENDING'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan
`

// Transitions a PENDING classification back to DRAFT, clearing the approver.
func (q *Queries) DeclineClassification(ctx context.Context, classificationID pgtype.UUID) (Classification, error) {
	row := q.db.QueryRow(ctx, declineClassification, classificationID)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const deleteClassification = `-- name: DeleteClassification :exec
DELETE FROM classification
WHERE classification_id = $1
  AND status = 'DRAFT'
`

// Permanently deletes a DRAFT classification.
func (q *Queries) DeleteClassification(ctx context.Context, classificationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassification, classificationID)
	return err
}

const findActiveClassification = `-- name: FindActiveClassification :one
select classification_id,
       name,
       created_on,
       effective_time,
       created_by,
       approved_by,
       status,
       plan
from classification
where effective_time < now()
  and status = 'ACTIVE'
order by effective_time DESC
limit 1
`

func (q *Queries) FindActiveClassification(ctx context.Context) (Classification, error) {
	row := q.db.QueryRow(ctx, findActiveClassification)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const findClassificationByID = `-- name: FindClassificationByID :one
SELECT classification_id, name, created_on, effective_time,
       created_by, approved_by, status, plan
FROM classification
WHERE classification_id = $1
`

// Retrieves a single classification record by its UUID.
func (q *Queries) FindClassificationByID(ctx context.Context, classificationID pgtype.UUID) (Classification, error) {
	row := q.db.QueryRow(ctx, findClassificationByID, classificationID)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const submitClassification = `-- name: SubmitClassification :one
UPDATE classification
SET status = 'PENDING'
WHERE classification_id = $1
  AND status = 'DRAFT'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan
`

// Transitions a DRAFT classification to PENDING (submitted for approval).
func (q *Queries) SubmitClassification(ctx context.Context, classificationID pgtype.UUID) (Classification, error) {
	row := q.db.QueryRow(ctx, submitClassification, classificationID)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}

const updateClassificationPlan = `-- name: UpdateClassificationPlan :one
UPDATE classification
SET name           = $2,
    effective_time = $3,
    plan           = $4
WHERE classification_id = $1
  AND status = 'DRAFT'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan
`

// Updates the name, effectiveTime, and plan of an existing DRAFT classification.
// Returns an error if no row matches (classification not found or not DRAFT).
func (q *Queries) UpdateClassificationPlan(ctx context.Context, classificationID pgtype.UUID, name string, effectiveTime pgtype.Timestamptz, plan []byte) (Classification, error) {
	row := q.db.QueryRow(ctx, updateClassificationPlan,
		classificationID,
		name,
		effectiveTime,
		plan,
	)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}
