// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classification.sql

package sqlc

import (
	"context"
)

const findActiveClassification = `-- name: FindActiveClassification :one
select classification_id,
       name,
       created_on,
       effective_time,
       created_by,
       approved_by,
       status,
       plan
from classification
where effective_time < now()
  and status = 'ACTIVE'
order by effective_time DESC
limit 1
`

func (q *Queries) FindActiveClassification(ctx context.Context) (Classification, error) {
	row := q.db.QueryRow(ctx, findActiveClassification)
	var i Classification
	err := row.Scan(
		&i.ClassificationID,
		&i.Name,
		&i.CreatedOn,
		&i.EffectiveTime,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.Status,
		&i.Plan,
	)
	return i, err
}
