// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: destination_groups.sql

package sqlc

import (
	"context"
)

const createDestinationGroup = `-- name: CreateDestinationGroup :one
INSERT INTO carrier_destination_group (group_name, region)
VALUES ($1, $2)
RETURNING group_name, region
`

// Inserts a new destination group and returns the full persisted row.
func (q *Queries) CreateDestinationGroup(ctx context.Context, groupName string, region string) (CarrierDestinationGroup, error) {
	row := q.db.QueryRow(ctx, createDestinationGroup, groupName, region)
	var i CarrierDestinationGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}

const deleteDestinationGroup = `-- name: DeleteDestinationGroup :exec
DELETE FROM carrier_destination_group
WHERE group_name = $1
`

// Deletes a destination group by group name.
func (q *Queries) DeleteDestinationGroup(ctx context.Context, groupName string) error {
	_, err := q.db.Exec(ctx, deleteDestinationGroup, groupName)
	return err
}

const destinationGroupByGroupName = `-- name: DestinationGroupByGroupName :one
SELECT group_name, region
FROM carrier_destination_group
WHERE group_name = $1
`

// Retrieves a single destination group record by its group name.
func (q *Queries) DestinationGroupByGroupName(ctx context.Context, groupName string) (CarrierDestinationGroup, error) {
	row := q.db.QueryRow(ctx, destinationGroupByGroupName, groupName)
	var i CarrierDestinationGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}

const updateDestinationGroup = `-- name: UpdateDestinationGroup :one
UPDATE carrier_destination_group
SET region = $2
WHERE group_name = $1
RETURNING group_name, region
`

// Updates an existing destination group by group name and returns the updated row.
func (q *Queries) UpdateDestinationGroup(ctx context.Context, groupName string, region string) (CarrierDestinationGroup, error) {
	row := q.db.QueryRow(ctx, updateDestinationGroup, groupName, region)
	var i CarrierDestinationGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}
