// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// The table of all carriers the network interacts with
type Carrier struct {
	// The PLMN for the carrier
	Plmn string
	// The last time the record was updated
	ModifiedOn pgtype.Timestamptz
	// The Mobile Country Code
	Mcc string
	// The Mobile Network Code
	Mnc pgtype.Text
	// The carrier name
	CarrierName string
	// The roaming source group for the carrier
	SourceGroup string
	// The destination group for the carrier
	DestinationGroup string
	// The country name
	CountryName string
	// The ISO country code
	Iso string
}

// The destination groups
type CarrierDestinationGroup struct {
	// The valid destination group name
	GroupName string
	// The full region name
	Region string
}

// Valid roaming source options
type CarrierSourceGroup struct {
	// The valid group name
	GroupName string
	// The full region name
	Region string
}

// The charging data session information
type ChargingDatum struct {
	// The session reference Id
	ChargingID string
	// The sequence number link to the request
	SequenceNumber int64
	// The last time the record was modified
	ModifiedOn pgtype.Timestamptz
	// The JSON structure of the charging data
	ChargeData []byte
}

// Trace table to store charging request and respons
type ChargingTrace struct {
	// Unique id for the trace
	TraceID pgtype.UUID
	// The timestamp of when the entry was made
	CreatedAt pgtype.Timestamptz
	// The JSONB request object
	Request []byte
	// The JSONB response object
	Response []byte
	// The execution time in milliseconds
	ExecutionTime int64
	// The charging id assigned by the NF
	ChargingID string
	// The sequence number as assigned by the NF
	SequenceNr int32
	// The MSISDN of the subscriber
	Msisdn string
}

// The classification store
type Classification struct {
	ClassificationID pgtype.UUID
	// The name of the classification rules
	Name string
	// The time the record was created
	CreatedOn pgtype.Timestamp
	// The time from which the plan is effective
	EffectiveTime pgtype.Timestamptz
	// The user that created the classification plan
	CreatedBy string
	// The user that approved the plan
	ApprovedBy pgtype.Text
	// The status of the plan: DRAFT, PENDING, ACTIVE and RETRIED
	Status string
	// The classification plan
	Plan []byte
}

// The number plans for the carriers
type NumberPlan struct {
	NumberID int64
	// The last time the record was updated
	ModifiedOn pgtype.Timestamptz
	// The name of the number plan
	Name string
	// The plmn of carrier the numbers belong too
	Plmn string
	// The first portion of the number
	NumberRange string
	// The maximum length a number can be.
	NumberLength int32
}

// Stores a JSON-based quota counter structure per subscriber
type Quotum struct {
	// Primary key for the quota record
	QuotaID pgtype.UUID
	// Timestamp used for optimistic locking and tracking updates
	LastModified pgtype.Timestamptz
	// The subscriber ID this quota is assigned to
	SubscriberID pgtype.UUID
	// The next time the quota should be evaluated (e.g., for expiry or renewal)
	NextActionTime pgtype.Timestamptz
	// The quota counter details stored as a JSONB structure
	Quota []byte
}

// The rateplan for all
type Rateplan struct {
	// The unique key for the plan
	ID int64
	// The plan id
	PlanID pgtype.UUID
	// The last time the rate plan was change
	ModifiedAt pgtype.Timestamptz
	// The type of plan SETTLEMENT, WHOLESALE, RETAIL
	PlanType string
	// The wholesaler the rate plan belongs to. Can be null if it is a SETTLEMENT plan or WHOLESALE plan
	WholesaleID pgtype.UUID
	// The rate plan name
	PlanName string
	// The YAML rate plan
	Rateplan []byte
	// The status of the rule plan: DRAFT, PENDING_APPROVAL, ACTIVE, RETIRED
	PlanStatus string
	// The user that created the rate plan
	CreatedBy string
	// The user that approved the rate plan
	ApprovedBy pgtype.Text
	// The time the rate plan become effective
	EffectiveAt pgtype.Timestamptz
}

// The shadow subscriber table
type Subscriber struct {
	// The subscriber id as allocated by the OSS service
	SubscriberID pgtype.UUID
	// The last time the record was modified
	ModifiedOn pgtype.Timestamptz
	// The rate plan id for the subscriber
	RateplanID pgtype.UUID
	// The Customer ID linked to the Subscriber ID
	CustomerID pgtype.UUID
	// The wholesaler Id the subscriber is provisioned on
	WholesaleID pgtype.UUID
	// The MSISDN linked to the subscriber
	Msisdn string
	// The ICCID linked to the subscriber
	Iccid string
	// The contract id linked to the msisdn
	ContractID pgtype.UUID
	// The status of the subscriber: ACTIVE, INACTIVE, BLOCKED
	Status string
	// The allow out of bundle charging flag
	AllowOobCharging bool
}

// The Wholesaler shadow database
type Wholesaler struct {
	ID pgtype.UUID
	// The last time the record was updated
	ModifiedOn pgtype.Timestamptz
	// True if the wholesaler is enabled for trading
	Active bool
	// The name of the wholesaler
	LegalName string
	// The display name of the wholesaler
	DisplayName string
	// The realm for the wholesaler
	Realm string
	// A comma delimited list of valid hosts
	Hosts []string
	// The NCHF Url for the wholesaler
	Nchfurl string
	// The ratelimit for NCHF requests
	Ratelimit pgtype.Numeric
	// The contract for the wholesaler
	ContractID pgtype.UUID
	// The rate plan to use for this wholesaler
	RateplanID pgtype.UUID
}
