// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: numberplan.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allNumbers = `-- name: AllNumbers :many
select number_plan.number_id, number_plan.modified_on, number_plan.name, number_plan.plmn, number_plan.number_range, number_plan.number_length, carrier.destination_group
from number_plan
inner join carrier on number_plan.plmn = carrier.plmn
`

type AllNumbersRow struct {
	NumberID         int64
	ModifiedOn       pgtype.Timestamptz
	Name             string
	Plmn             string
	NumberRange      string
	NumberLength     int32
	DestinationGroup string
}

func (q *Queries) AllNumbers(ctx context.Context) ([]AllNumbersRow, error) {
	rows, err := q.db.Query(ctx, allNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllNumbersRow
	for rows.Next() {
		var i AllNumbersRow
		if err := rows.Scan(
			&i.NumberID,
			&i.ModifiedOn,
			&i.Name,
			&i.Plmn,
			&i.NumberRange,
			&i.NumberLength,
			&i.DestinationGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
