// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuota = `-- name: CreateQuota :one
insert into quota(quota_id, last_modified, subscriber_id, next_action_time, quota)
VALUES ($1, now(), $2, now(), $3)
returning quota_id, last_modified, subscriber_id, next_action_time, quota
`

func (q *Queries) CreateQuota(ctx context.Context, quotaID pgtype.UUID, subscriberID pgtype.UUID, quota []byte) (Quotum, error) {
	row := q.db.QueryRow(ctx, createQuota, quotaID, subscriberID, quota)
	var i Quotum
	err := row.Scan(
		&i.QuotaID,
		&i.LastModified,
		&i.SubscriberID,
		&i.NextActionTime,
		&i.Quota,
	)
	return i, err
}

const findQuota = `-- name: FindQuota :one
select quota_id, last_modified, subscriber_id, next_action_time, quota
from quota
where subscriber_id = $1
`

func (q *Queries) FindQuota(ctx context.Context, subscriberID pgtype.UUID) (Quotum, error) {
	row := q.db.QueryRow(ctx, findQuota, subscriberID)
	var i Quotum
	err := row.Scan(
		&i.QuotaID,
		&i.LastModified,
		&i.SubscriberID,
		&i.NextActionTime,
		&i.Quota,
	)
	return i, err
}

const updateQuota = `-- name: UpdateQuota :execrows
update quota
set last_modified=$4,
    quota=$3
where quota_id = $1
  and last_modified = $2
`

func (q *Queries) UpdateQuota(ctx context.Context, quotaID pgtype.UUID, lastModified pgtype.Timestamptz, quota []byte, lastModified_2 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuota,
		quotaID,
		lastModified,
		quota,
		lastModified_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
