// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rateplan.sql

package sqlc

import (
	"context"
)

const findActiveRatePlans = `-- name: FindActiveRatePlans :many
select id, plan_id, modified_at, plan_type, wholesale_id, plan_name, rateplan, plan_status, created_by, approved_by, effective_at
from rateplan
where plan_status = 'ACTIVE'
  and effective_at < now() -- all plans that are effective now or in the past
order by plan_type,
         effective_at desc
`

func (q *Queries) FindActiveRatePlans(ctx context.Context) ([]Rateplan, error) {
	rows, err := q.db.Query(ctx, findActiveRatePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rateplan
	for rows.Next() {
		var i Rateplan
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ModifiedAt,
			&i.PlanType,
			&i.WholesaleID,
			&i.PlanName,
			&i.Rateplan,
			&i.PlanStatus,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
