// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rateplan.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRatePlan = `-- name: ApproveRatePlan :one
UPDATE rateplan
SET plan_status = 'ACTIVE',
    approved_by = $2,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'PENDING'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

// Transitions the PENDING version of a logical plan to ACTIVE and records the approver.
func (q *Queries) ApproveRatePlan(ctx context.Context, planID pgtype.UUID, approvedBy pgtype.Text) (Rateplan, error) {
	row := q.db.QueryRow(ctx, approveRatePlan, planID, approvedBy)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const createRatePlan = `-- name: CreateRatePlan :one
INSERT INTO rateplan (plan_id, plan_type, wholesale_id, plan_name, rateplan, created_by, effective_at, plan_status, modified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'DRAFT', NOW())
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

type CreateRatePlanParams struct {
	PlanID      pgtype.UUID
	PlanType    string
	WholesaleID pgtype.UUID
	PlanName    string
	Rateplan    []byte
	CreatedBy   string
	EffectiveAt pgtype.Timestamptz
}

// Inserts a new rate plan version in DRAFT status.
// plan_id is generated by the application. wholesale_id is null for non-RETAIL plans.
func (q *Queries) CreateRatePlan(ctx context.Context, arg CreateRatePlanParams) (Rateplan, error) {
	row := q.db.QueryRow(ctx, createRatePlan,
		arg.PlanID,
		arg.PlanType,
		arg.WholesaleID,
		arg.PlanName,
		arg.Rateplan,
		arg.CreatedBy,
		arg.EffectiveAt,
	)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const declineRatePlan = `-- name: DeclineRatePlan :one
UPDATE rateplan
SET plan_status = 'DRAFT',
    approved_by = NULL,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'PENDING'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

// Transitions the PENDING version of a logical plan back to DRAFT, clearing the approver.
func (q *Queries) DeclineRatePlan(ctx context.Context, planID pgtype.UUID) (Rateplan, error) {
	row := q.db.QueryRow(ctx, declineRatePlan, planID)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const deleteRatePlan = `-- name: DeleteRatePlan :exec
DELETE FROM rateplan
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
`

// Permanently deletes the DRAFT version of a logical plan.
func (q *Queries) DeleteRatePlan(ctx context.Context, planID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRatePlan, planID)
	return err
}

const findActiveRatePlans = `-- name: FindActiveRatePlans :many
select id, plan_id, modified_at, plan_type, wholesale_id, plan_name, rateplan, plan_status, created_by, approved_by, effective_at
from rateplan
where plan_status = 'ACTIVE'
  and effective_at < now() -- all plans that are effective now or in the past
order by plan_type,
         effective_at desc
`

func (q *Queries) FindActiveRatePlans(ctx context.Context) ([]Rateplan, error) {
	rows, err := q.db.Query(ctx, findActiveRatePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rateplan
	for rows.Next() {
		var i Rateplan
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ModifiedAt,
			&i.PlanType,
			&i.WholesaleID,
			&i.PlanName,
			&i.Rateplan,
			&i.PlanStatus,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLatestRatePlanByPlanId = `-- name: FindLatestRatePlanByPlanId :one

SELECT id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
       rateplan, plan_status, created_by, approved_by, effective_at
FROM rateplan
WHERE plan_id = $1
ORDER BY effective_at DESC, id DESC
LIMIT 1
`

// order by effective_at descending so that the most recent plan is first
// Returns the most recent version of a logical rate plan by plan_id.
func (q *Queries) FindLatestRatePlanByPlanId(ctx context.Context, planID pgtype.UUID) (Rateplan, error) {
	row := q.db.QueryRow(ctx, findLatestRatePlanByPlanId, planID)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const latestRatePlanByType = `-- name: LatestRatePlanByType :many
SELECT DISTINCT ON (plan_id)
    id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
    rateplan, plan_status, created_by, approved_by, effective_at
FROM rateplan
WHERE plan_type = $1
  AND ($2::uuid IS NULL OR wholesale_id = $2)
ORDER BY plan_id, effective_at DESC, id DESC
`

// Returns the most recent version (by effective_at, id) of each logical plan for the given planType.
// For RETAIL plans pass the tenant's wholesale_id; for SETTLEMENT/WHOLESALE pass NULL.
func (q *Queries) LatestRatePlanByType(ctx context.Context, planType string, column2 pgtype.UUID) ([]Rateplan, error) {
	rows, err := q.db.Query(ctx, latestRatePlanByType, planType, column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rateplan
	for rows.Next() {
		var i Rateplan
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.ModifiedAt,
			&i.PlanType,
			&i.WholesaleID,
			&i.PlanName,
			&i.Rateplan,
			&i.PlanStatus,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitRatePlan = `-- name: SubmitRatePlan :one
UPDATE rateplan
SET plan_status = 'PENDING',
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

// Transitions the DRAFT version of a logical plan to PENDING.
func (q *Queries) SubmitRatePlan(ctx context.Context, planID pgtype.UUID) (Rateplan, error) {
	row := q.db.QueryRow(ctx, submitRatePlan, planID)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const updateRatePlan = `-- name: UpdateRatePlan :one
UPDATE rateplan
SET plan_name    = $2,
    plan_type    = $3,
    effective_at = $4,
    rateplan     = $5,
    modified_at  = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

type UpdateRatePlanParams struct {
	PlanID      pgtype.UUID
	PlanName    string
	PlanType    string
	EffectiveAt pgtype.Timestamptz
	Rateplan    []byte
}

// Updates the name, type, effectiveAt, and rateplan JSONB of the DRAFT version of a logical plan.
// Guards against modifying non-DRAFT versions.
func (q *Queries) UpdateRatePlan(ctx context.Context, arg UpdateRatePlanParams) (Rateplan, error) {
	row := q.db.QueryRow(ctx, updateRatePlan,
		arg.PlanID,
		arg.PlanName,
		arg.PlanType,
		arg.EffectiveAt,
		arg.Rateplan,
	)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}

const updateRatePlanRules = `-- name: UpdateRatePlanRules :one
UPDATE rateplan
SET rateplan    = $2,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at
`

// Updates only the rateplan JSONB of the DRAFT version of a logical plan.
// TODO: confirm whether this or UpdateRatePlan is the one to keep in production.
func (q *Queries) UpdateRatePlanRules(ctx context.Context, planID pgtype.UUID, rateplan []byte) (Rateplan, error) {
	row := q.db.QueryRow(ctx, updateRatePlanRules, planID, rateplan)
	var i Rateplan
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.ModifiedAt,
		&i.PlanType,
		&i.WholesaleID,
		&i.PlanName,
		&i.Rateplan,
		&i.PlanStatus,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.EffectiveAt,
	)
	return i, err
}
