// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: source_groups.sql

package sqlc

import (
	"context"
)

const createSourceGroup = `-- name: CreateSourceGroup :one
INSERT INTO carrier_source_group (group_name, region)
VALUES ($1, $2)
RETURNING group_name, region
`

// Inserts a new source group and returns the full persisted row.
func (q *Queries) CreateSourceGroup(ctx context.Context, groupName string, region string) (CarrierSourceGroup, error) {
	row := q.db.QueryRow(ctx, createSourceGroup, groupName, region)
	var i CarrierSourceGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}

const deleteSourceGroup = `-- name: DeleteSourceGroup :exec
DELETE FROM carrier_source_group
WHERE group_name = $1
`

// Deletes a source group by group name.
func (q *Queries) DeleteSourceGroup(ctx context.Context, groupName string) error {
	_, err := q.db.Exec(ctx, deleteSourceGroup, groupName)
	return err
}

const sourceGroupByGroupName = `-- name: SourceGroupByGroupName :one
SELECT group_name, region
FROM carrier_source_group
WHERE group_name = $1
`

// Retrieves a single source group record by its group name.
func (q *Queries) SourceGroupByGroupName(ctx context.Context, groupName string) (CarrierSourceGroup, error) {
	row := q.db.QueryRow(ctx, sourceGroupByGroupName, groupName)
	var i CarrierSourceGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}

const updateSourceGroup = `-- name: UpdateSourceGroup :one
UPDATE carrier_source_group
SET region = $2
WHERE group_name = $1
RETURNING group_name, region
`

// Updates an existing source group by group name and returns the updated row.
func (q *Queries) UpdateSourceGroup(ctx context.Context, groupName string, region string) (CarrierSourceGroup, error) {
	row := q.db.QueryRow(ctx, updateSourceGroup, groupName, region)
	var i CarrierSourceGroup
	err := row.Scan(&i.GroupName, &i.Region)
	return i, err
}
