// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber_wholesaler.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findSubscriberWithWholesalerByMSISDN = `-- name: FindSubscriberWithWholesalerByMSISDN :one
SELECT
    -- subscriber
    s.subscriber_id,
    s.modified_on,
    s.rateplan_id,
    s.customer_id,
    s.wholesale_id,
    s.msisdn,
    s.iccid,
    s.contract_id,
    s.status,
    s.allow_oob_charging,

    -- wholesaler (aliased to avoid name collisions)
    w.id           AS wholesaler_id,
    w.modified_on  AS wholesaler_modified_on,
    w.active       AS wholesaler_active,
    w.legal_name   AS wholesaler_legal_name,
    w.display_name AS wholesaler_display_name,
    w.realm        AS wholesaler_realm,
    w.hosts        AS wholesaler_hosts,
    w.nchfurl      AS wholesaler_nchfurl,
    w.ratelimit    AS wholesaler_ratelimit,
    w.contract_id  AS wholesaler_contract_id,
    w.rateplan_id  AS wholesaler_rateplan_id
FROM subscriber s
         JOIN wholesaler w ON w.id = s.wholesale_id
WHERE s.msisdn = $1
`

type FindSubscriberWithWholesalerByMSISDNRow struct {
	SubscriberID          pgtype.UUID
	ModifiedOn            pgtype.Timestamptz
	RateplanID            pgtype.UUID
	CustomerID            pgtype.UUID
	WholesaleID           pgtype.UUID
	Msisdn                string
	Iccid                 string
	ContractID            pgtype.UUID
	Status                string
	AllowOobCharging      bool
	WholesalerID          pgtype.UUID
	WholesalerModifiedOn  pgtype.Timestamptz
	WholesalerActive      bool
	WholesalerLegalName   string
	WholesalerDisplayName string
	WholesalerRealm       string
	WholesalerHosts       []string
	WholesalerNchfurl     string
	WholesalerRatelimit   pgtype.Numeric
	WholesalerContractID  pgtype.UUID
	WholesalerRateplanID  pgtype.UUID
}

func (q *Queries) FindSubscriberWithWholesalerByMSISDN(ctx context.Context, msisdn string) (FindSubscriberWithWholesalerByMSISDNRow, error) {
	row := q.db.QueryRow(ctx, findSubscriberWithWholesalerByMSISDN, msisdn)
	var i FindSubscriberWithWholesalerByMSISDNRow
	err := row.Scan(
		&i.SubscriberID,
		&i.ModifiedOn,
		&i.RateplanID,
		&i.CustomerID,
		&i.WholesaleID,
		&i.Msisdn,
		&i.Iccid,
		&i.ContractID,
		&i.Status,
		&i.AllowOobCharging,
		&i.WholesalerID,
		&i.WholesalerModifiedOn,
		&i.WholesalerActive,
		&i.WholesalerLegalName,
		&i.WholesalerDisplayName,
		&i.WholesalerRealm,
		&i.WholesalerHosts,
		&i.WholesalerNchfurl,
		&i.WholesalerRatelimit,
		&i.WholesalerContractID,
		&i.WholesalerRateplanID,
	)
	return i, err
}
