// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriber.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscriber
WHERE subscriber_id = $1
`

// Hard-deletes a subscriber by subscriber_id.
func (q *Queries) DeleteSubscriber(ctx context.Context, subscriberID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscriber, subscriberID)
	return err
}

const insertSubscriber = `-- name: InsertSubscriber :exec
INSERT INTO subscriber (subscriber_id, rateplan_id, customer_id, wholesale_id, msisdn, iccid, contract_id, status, allow_oob_charging)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertSubscriberParams struct {
	SubscriberID     pgtype.UUID
	RateplanID       pgtype.UUID
	CustomerID       pgtype.UUID
	WholesaleID      pgtype.UUID
	Msisdn           string
	Iccid            string
	ContractID       pgtype.UUID
	Status           string
	AllowOobCharging bool
}

// Inserts a new subscriber row. modified_on is set to NOW() by the DB default.
func (q *Queries) InsertSubscriber(ctx context.Context, arg InsertSubscriberParams) error {
	_, err := q.db.Exec(ctx, insertSubscriber,
		arg.SubscriberID,
		arg.RateplanID,
		arg.CustomerID,
		arg.WholesaleID,
		arg.Msisdn,
		arg.Iccid,
		arg.ContractID,
		arg.Status,
		arg.AllowOobCharging,
	)
	return err
}

const updateSubscriber = `-- name: UpdateSubscriber :exec
UPDATE subscriber
SET rateplan_id        = $2,
    customer_id        = $3,
    wholesale_id       = $4,
    msisdn             = $5,
    iccid              = $6,
    contract_id        = $7,
    status             = $8,
    allow_oob_charging = $9,
    modified_on        = NOW()
WHERE subscriber_id = $1
`

type UpdateSubscriberParams struct {
	SubscriberID     pgtype.UUID
	RateplanID       pgtype.UUID
	CustomerID       pgtype.UUID
	WholesaleID      pgtype.UUID
	Msisdn           string
	Iccid            string
	ContractID       pgtype.UUID
	Status           string
	AllowOobCharging bool
}

// Updates all mutable fields for an existing subscriber. modified_on is refreshed to NOW().
func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) error {
	_, err := q.db.Exec(ctx, updateSubscriber,
		arg.SubscriberID,
		arg.RateplanID,
		arg.CustomerID,
		arg.WholesaleID,
		arg.Msisdn,
		arg.Iccid,
		arg.ContractID,
		arg.Status,
		arg.AllowOobCharging,
	)
	return err
}
