// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wholesaler.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allWholesalers = `-- name: AllWholesalers :many
SELECT id, hosts FROM wholesaler WHERE active = true
`

type AllWholesalersRow struct {
	ID    pgtype.UUID
	Hosts []string
}

// Returns all active wholesaler records. Used by the tenant resolver to build
// the hostname → wholesale_id lookup map.
func (q *Queries) AllWholesalers(ctx context.Context) ([]AllWholesalersRow, error) {
	rows, err := q.db.Query(ctx, allWholesalers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllWholesalersRow
	for rows.Next() {
		var i AllWholesalersRow
		if err := rows.Scan(&i.ID, &i.Hosts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
