-- name: FindActiveClassification :one
select classification_id,
       name,
       created_on,
       effective_time,
       created_by,
       approved_by,
       status,
       plan
from classification
where effective_time < now()
  and status = 'ACTIVE'
order by effective_time DESC
limit 1;

-- name: FindClassificationByID :one
-- Retrieves a single classification record by its UUID.
SELECT classification_id, name, created_on, effective_time,
       created_by, approved_by, status, plan
FROM classification
WHERE classification_id = $1;

-- name: CreateClassification :one
-- Inserts a new classification in DRAFT status and returns the full persisted row.
-- classification_id is generated by the application (uuid.New()).
INSERT INTO classification (classification_id, name, effective_time, created_by, plan, status)
VALUES ($1, $2, $3, $4, $5, 'DRAFT')
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan;

-- name: UpdateClassificationPlan :one
-- Updates the name, effectiveTime, and plan of an existing DRAFT classification.
-- Returns an error if no row matches (classification not found or not DRAFT).
UPDATE classification
SET name           = $2,
    effective_time = $3,
    plan           = $4
WHERE classification_id = $1
  AND status = 'DRAFT'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan;

-- name: SubmitClassification :one
-- Transitions a DRAFT classification to PENDING (submitted for approval).
UPDATE classification
SET status = 'PENDING'
WHERE classification_id = $1
  AND status = 'DRAFT'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan;

-- name: ApproveClassification :one
-- Transitions a PENDING classification to ACTIVE and records the approver.
UPDATE classification
SET status      = 'ACTIVE',
    approved_by = $2
WHERE classification_id = $1
  AND status = 'PENDING'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan;

-- name: DeclineClassification :one
-- Transitions a PENDING classification back to DRAFT, clearing the approver.
UPDATE classification
SET status      = 'DRAFT',
    approved_by = NULL
WHERE classification_id = $1
  AND status = 'PENDING'
RETURNING classification_id, name, created_on, effective_time,
          created_by, approved_by, status, plan;

-- name: DeleteClassification :exec
-- Permanently deletes a DRAFT classification.
DELETE FROM classification
WHERE classification_id = $1
  AND status = 'DRAFT';
