-- name: FindActiveRatePlans :many
select *
from rateplan
where plan_status = 'ACTIVE'
  and effective_at < now() -- all plans that are effective now or in the past
order by plan_type,
         effective_at desc; -- order by effective_at descending so that the most recent plan is first

-- name: FindLatestRatePlanByPlanId :one
-- Returns the most recent version of a logical rate plan by plan_id.
SELECT id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
       rateplan, plan_status, created_by, approved_by, effective_at
FROM rateplan
WHERE plan_id = $1
ORDER BY effective_at DESC, id DESC
LIMIT 1;

-- name: CreateRatePlan :one
-- Inserts a new rate plan version in DRAFT status.
-- plan_id is generated by the application. wholesale_id is null for non-RETAIL plans.
INSERT INTO rateplan (plan_id, plan_type, wholesale_id, plan_name, rateplan, created_by, effective_at, plan_status, modified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'DRAFT', NOW())
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: UpdateRatePlan :one
-- Updates the name, type, effectiveAt, and rateplan JSONB of the DRAFT version of a logical plan.
-- Guards against modifying non-DRAFT versions.
UPDATE rateplan
SET plan_name    = $2,
    plan_type    = $3,
    effective_at = $4,
    rateplan     = $5,
    modified_at  = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: UpdateRatePlanRules :one
-- Updates only the rateplan JSONB of the DRAFT version of a logical plan.
-- TODO: confirm whether this or UpdateRatePlan is the one to keep in production.
UPDATE rateplan
SET rateplan    = $2,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: SubmitRatePlan :one
-- Transitions the DRAFT version of a logical plan to PENDING.
UPDATE rateplan
SET plan_status = 'PENDING',
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'DRAFT'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: ApproveRatePlan :one
-- Transitions the PENDING version of a logical plan to ACTIVE and records the approver.
UPDATE rateplan
SET plan_status = 'ACTIVE',
    approved_by = $2,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'PENDING'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: DeclineRatePlan :one
-- Transitions the PENDING version of a logical plan back to DRAFT, clearing the approver.
UPDATE rateplan
SET plan_status = 'DRAFT',
    approved_by = NULL,
    modified_at = NOW()
WHERE plan_id     = $1
  AND plan_status = 'PENDING'
RETURNING id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
          rateplan, plan_status, created_by, approved_by, effective_at;

-- name: DeleteRatePlan :exec
-- Permanently deletes the DRAFT version of a logical plan.
DELETE FROM rateplan
WHERE plan_id     = $1
  AND plan_status = 'DRAFT';

-- name: LatestRatePlanByType :many
-- Returns the most recent version (by effective_at, id) of each logical plan for the given planType.
-- For RETAIL plans pass the tenant's wholesale_id; for SETTLEMENT/WHOLESALE pass NULL.
SELECT DISTINCT ON (plan_id)
    id, plan_id, modified_at, plan_type, wholesale_id, plan_name,
    rateplan, plan_status, created_by, approved_by, effective_at
FROM rateplan
WHERE plan_type = $1
  AND ($2::uuid IS NULL OR wholesale_id = $2)
ORDER BY plan_id, effective_at DESC, id DESC;
